.TH ZATACKA 6 "February  5, 2006"
.SH NAME
zatacka \- Arcade multiplayer game like nibbles
.SH SYNOPSIS
.B zatacka
.br
.SH DESCRIPTION
This manual page documents briefly the
.B zatacka
command.
.PP
\fBzatacka\fP is an arcade multiplayer game for 2 \- 6 players on one
keyboard, clone of Achtung die Kurve classical dos game. You handle
your line and you must sidetrack lines of other players and of course
walls. When some player dies, survival gets one point. When only one
player is left alive, the round is finished. Each game has eleven rounds.
.SH AUTHOR
zatacka was written by Mage <admin@zatacka.xf.cz>.
.PP
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@linuks.mine.nu>,
for the Debian project (but may be used by others).
